### ISSUE TITLE
Incorrect message length calc

### ISSUE THREAD

**Issue by Kirlik** [hsaturn/TinyMqtt#13]
It looks like message length(function "incoming") should be calculated this way:
		case Length:
			size += (in_byte  & 0x7F) *size_mult;
			size_mult *=0x80;
.............

size_mult  should initialize with "1"  in FixedHeader section

**Comment by hsaturn** [comment]
Thanks for the report, I'll have a look this evening.

**Comment by hsaturn** [comment]
Sorry, I'm very busy these days, I'll take care of it soon

**Comment by hsaturn** [comment]
Hi Kirlik

Thanks for your report, the 3F has been fixed to 7F [here](https://github.com/hsaturn/TinyMqtt/commit/56a2be621f446cf8f0801e9a81cdc19cc42dbcc5).

Unfortunately, I cannot write a unit test for some reasons but the bug should be fixed.

Best regards

**Comment by Kirlik** [comment]
I think it's still wrong. The message length comes with big-endian. Consider using my code.

**Comment by hsaturn** [comment]
Hello Jeremy

Thanks for making me look again at the specification, and you're right, then I'll fix that very soon

**Comment by hsaturn** [comment]
I do not want to handle > 16k messages. I consider that this is too long for a embedded device.
I cannot see yet a use case where > 16k msg could be of any interrest for an Esp.

Feel free to comment if you think this is really to low.

Best regards

**Comment by Kirlik** [comment]
But at least a couple of thousand bytes would be nice to process. For example there are packets with a length of more than 1 byte in the "tasmata" firmware for Sonoff relays  
  
>Понедельник, 9 августа 2021, 11:52 +03:00 от hsaturn ***@***.***>:
> 
> 
>I do not want to handle > 16k messages. I consider that this is too long for a embedded device.
>I cannot see yet a use case where > 16k msg could be of any interrest for an Esp.
>Feel free to comment if you think this is really to low.
>Best regards
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
С уважением,
Кирилл Петюшин

**Comment by hsaturn** [comment]
I do agree !

This is why I've set the limit at 4096 bytes (see [there](https://github.com/hsaturn/TinyMqtt/blob/main/src/TinyMqtt.h#L67)) in the last release.

I think that 4K allows to handle most of situations, including the 2000 you mentioned.
The hard limit is 16k, I consider that more than 16k on ESP which have 96K of memory is fair.
